In [ ]:
import pandas as pd
df = pd.read_csv("/content/Supermarket Sales 2.csv")
#df

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5053 entries, 0 to 5052
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           5053 non-null   object
 1   Branch         5053 non-null   object
 2   Customer type  5053 non-null   object
 3   Gender         5053 non-null   object
 4   Product line   5053 non-null   object
 5   Unit price     5053 non-null   float64
 6   Quantity       5053 non-null   int64
 7   Payment        5053 non-null   object
 8   Rating         5053 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 355.4+ KB

In [ ]:
df.describe()

        Unit price     Quantity       Rating
count  5053.000000  5053.000000  5053.000000
mean     39.692988     4.593509     6.884029
std      29.557474     2.787934     1.710245
min       2.010000     1.000000     3.000000
25%      11.630000     2.000000     5.600000
50%      33.900000     4.000000     7.100000
75%      64.940000     7.000000     8.200000
max      99.960000    10.000000    10.000000

In [ ]:
df.head()

,Date,Branch,Customer type,Gender,Product line,Unit price,Quantity,Payment,Rating
0,1/1/2024,Brooklyn,Member,Female,Food & Beverages,84.63,10,Credit card,9.0
1,1/1/2024,Queens,Normal,Female,Electronics,63.22,2,Cash,8.5
2,1/1/2024,Brooklyn,Normal,Female,Electronics,74.71,6,Cash,6.7
3,1/1/2024,Queens,Member,Female,Sports & Travel,36.98,10,Credit card,7.0
4,1/1/2024,Manhattan,Member,Female,Sports & Travel,27.04,4,Ewallet,6.9

In [ ]:
# Adding a column 'Revenue'
df["Revenue"] = df['Unit price'] * df['Quantity']
df.head(3)

,Date,Branch,Customer type,Gender,Product line,Unit price,Quantity,Payment,Rating,Revenue
0,1/1/2024,Brooklyn,Member,Female,Food & Beverages,84.63,10,Credit card,9.0,846.30
1,1/1/2024,Queens,Normal,Female,Electronics,63.22,2,Cash,8.5,126.44
2,1/1/2024,Brooklyn,Normal,Female,Electronics,74.71,6,Cash,6.7,448.26

In [ ]:
#Total revenue:
total_revenue = df['Revenue'].sum()
print('Total revenue = ', total_revenue)

Total revenue =  942544.85

In [ ]:
# Average receipt amount:
average_receipt = df['Revenue'].mean().round(2)
print('Average receipt: ', average_receipt)

Average receipt:  186.53

In [ ]:
# Average check amount per day:

revenue_per_day = df.groupby('Date')['Revenue'].sum()
revenue_per_day
average_check_per_day = total_revenue / 365
print('Average check per day = :', average_check_per_day.round(2))

Average check per day = : 2582.31

In [ ]:
#Top product categories:
df_top = (df.groupby('Product line', as_index=False)['Revenue'].sum().sort_values(by = 'Revenue', ascending=False))
df_top

       Product line    Revenue
4  Home & Lifestyle  197260.56
3   Health & Beauty  168570.61
5   Sports & Travel  164252.94
0       Electronics  159259.10
2  Food & Beverages  151357.73
1    Fashion & Accs  101843.91

In [ ]:
# The share of goods in revenue:
#type(df_top_10)
df_top['Share of goods'] = df_top['Revenue'] / total_revenue
df_top

       Product line    Revenue  Share of goods
4  Home & Lifestyle  197260.56        0.209285
3   Health & Beauty  168570.61        0.178846
5   Sports & Travel  164252.94        0.174265
0       Electronics  159259.10        0.168967
2  Food & Beverages  151357.73        0.160584
1    Fashion & Accs  101843.91        0.108052

In [ ]:
# Time-based sales analysis: days
# Convert the 'Date' column from string to datetime
try:
    df['Date'] = pd.to_datetime(df['Date'])
    print("Date column successfully converted to datetime")
except Exception as e:
    print("Error converting Date column:", e)

daily_revenue = df.groupby('Date', as_index=False)['Revenue'].sum()
daily_revenue

Date column successfully converted to datetime

          Date  Revenue
0   2024-01-01  4519.22
1   2024-01-02  1852.86
2   2024-01-03  1979.17
3   2024-01-04  1546.37
4   2024-01-05  3368.27
..         ...      ...
360 2024-12-27  2669.39
361 2024-12-28  4160.61
362 2024-12-29  6320.11
363 2024-12-30  5833.15
364 2024-12-31  3532.79

[365 rows x 2 columns]

In [ ]:
# Revenue during the week:
daily_revenue['Day_type'] = daily_revenue['Date'].dt.weekday.apply(lambda x: 'Weekend' if x >=5 else 'Workday')
daily_revenue

          Date  Revenue Day_type
0   2024-01-01  4519.22  Workday
1   2024-01-02  1852.86  Workday
2   2024-01-03  1979.17  Workday
3   2024-01-04  1546.37  Workday
4   2024-01-05  3368.27  Workday
..         ...      ...      ...
360 2024-12-27  2669.39  Workday
361 2024-12-28  4160.61  Weekend
362 2024-12-29  6320.11  Weekend
363 2024-12-30  5833.15  Workday
364 2024-12-31  3532.79  Workday

[365 rows x 3 columns]

In [ ]:
# Time-based sales analysis: months
df['Month'] = df['Date'].dt.to_period('M').dt.to_timestamp()
#df.head(3)
monthly_revenue = (df.groupby(['Month','Branch'], as_index=False)['Revenue'].sum())
monthly_revenue

        Month     Branch   Revenue
0  2024-01-01   Brooklyn  35405.77
1  2024-01-01  Manhattan  36839.17
2  2024-01-01     Queens  38509.22
3  2024-02-01   Brooklyn  34276.21
4  2024-02-01  Manhattan  28822.41
5  2024-02-01     Queens  31663.02
6  2024-03-01   Brooklyn  32949.85
7  2024-03-01  Manhattan  35865.83
8  2024-03-01     Queens  35427.66
9  2024-04-01   Brooklyn  42729.61
10 2024-04-01  Manhattan  39123.73
11 2024-04-01     Queens  50230.54
12 2024-05-01   Brooklyn  25654.59
13 2024-05-01  Manhattan  23204.47
14 2024-05-01     Queens  12096.72
15 2024-06-01   Brooklyn  13796.19
16 2024-06-01  Manhattan   7934.63
17 2024-06-01     Queens   7152.59
18 2024-07-01   Brooklyn   8327.56
19 2024-07-01  Manhattan   9603.26
20 2024-07-01     Queens   4237.21
21 2024-08-01   Brooklyn   7054.37
22 2024-08-01  Manhattan   8643.81
23 2024-08-01     Queens   3741.97
24 2024-09-01   Brooklyn  27265.14
25 2024-09-01  Manhattan  23999.05
26 2024-09-01     Queens  25625.88
27 2024-10-01   Brooklyn  24068.87
28 2024-10-01  Manhattan  22980.78
29 2024-10-01     Queens  25601.99
30 2024-11-01   Brooklyn  30459.85
31 2024-11-01  Manhattan  33818.88
32 2024-11-01     Queens  37138.90
33 2024-12-01   Brooklyn  37717.47
34 2024-12-01  Manhattan  39160.53
35 2024-12-01     Queens  41417.12

In [ ]:
# Time-based prices analysis: months

monthly_price = (df.groupby(['Month', 'Branch'], as_index=False)['Unit price'].mean())
monthly_price

        Month     Branch  Unit price
0  2024-01-01   Brooklyn   58.958649
1  2024-01-01  Manhattan   53.357395
2  2024-01-01     Queens   56.229098
3  2024-02-01   Brooklyn   55.120877
4  2024-02-01  Manhattan   57.372604
5  2024-02-01     Queens   58.492673
6  2024-03-01   Brooklyn   53.704018
7  2024-03-01  Manhattan   53.897874
8  2024-03-01     Queens   55.649434
9  2024-04-01   Brooklyn   57.928808
10 2024-04-01  Manhattan   56.726043
11 2024-04-01     Queens   57.758408
12 2024-05-01   Brooklyn   53.625318
13 2024-05-01  Manhattan   57.504354
14 2024-05-01     Queens   52.788763
15 2024-06-01   Brooklyn   30.801829
16 2024-06-01  Manhattan   26.339091
17 2024-06-01     Queens   26.279725
18 2024-07-01   Brooklyn   22.730769
19 2024-07-01  Manhattan   23.265592
20 2024-07-01     Queens   19.685326
21 2024-08-01   Brooklyn   21.868369
22 2024-08-01  Manhattan   23.735778
23 2024-08-01     Queens   18.669310
24 2024-09-01   Brooklyn   32.225346
25 2024-09-01  Manhattan   32.126577
26 2024-09-01     Queens   30.510625
27 2024-10-01   Brooklyn   31.181088
28 2024-10-01  Manhattan   31.771269
29 2024-10-01     Queens   34.622431
30 2024-11-01   Brooklyn   31.867803
31 2024-11-01  Manhattan   33.237732
32 2024-11-01     Queens   34.554579
33 2024-12-01   Brooklyn   35.669448
34 2024-12-01  Manhattan   36.787901
35 2024-12-01     Queens   36.390631

In [ ]:
# Revenue by branches:
branch_revenue = (df.groupby('Branch', as_index=False)['Revenue'].sum())
branch_revenue

      Branch    Revenue
0   Brooklyn  319705.48
1  Manhattan  309996.55
2     Queens  312842.82

In [ ]:
# The share of cash and card payments:
cash_and_card = (df.groupby('Payment', as_index=False)['Revenue'].sum())
cash_and_card

       Payment    Revenue
0         Cash  304622.65
1  Credit card  311230.89
2      Ewallet  326691.31

In [ ]:
# The largest receipt:
top_receipt = df['Revenue'].idxmax()
df.loc[top_receipt]

Date             2024-02-15 00:00:00
Branch                        Queens
Customer type                 Member
Gender                        Female
Product line          Fashion & Accs
Unit price                      99.3
Quantity                          10
Payment                  Credit card
Rating                           6.6
Revenue                        993.0
Month            2024-02-01 00:00:00
Name: 527, dtype: object

In [ ]:
# Sales analysis by product line and branch:
analysis_prod_branch = (df.groupby(['Product line', 'Branch'], as_index=False)['Revenue'].sum())
analysis_prod_branch

        Product line     Branch   Revenue
0        Electronics   Brooklyn  55028.11
1        Electronics  Manhattan  53562.92
2        Electronics     Queens  50668.07
3     Fashion & Accs   Brooklyn  33284.28
4     Fashion & Accs  Manhattan  28227.90
5     Fashion & Accs     Queens  40331.73
6   Food & Beverages   Brooklyn  46384.15
7   Food & Beverages  Manhattan  50240.99
8   Food & Beverages     Queens  54732.59
9    Health & Beauty   Brooklyn  62766.14
10   Health & Beauty  Manhattan  49906.52
11   Health & Beauty     Queens  55897.95
12  Home & Lifestyle   Brooklyn  66728.97
13  Home & Lifestyle  Manhattan  74494.27
14  Home & Lifestyle     Queens  56037.32
15   Sports & Travel   Brooklyn  55513.83
16   Sports & Travel  Manhattan  53563.95
17   Sports & Travel     Queens  55175.16

In [ ]:
# Revenue by customer type monthly:
customer_month_revenue = (df.groupby(['Month', 'Customer type'], as_index=False)['Revenue'].sum())
customer_month_revenue

        Month Customer type   Revenue
0  2024-01-01        Member  55156.98
1  2024-01-01        Normal  55597.18
2  2024-02-01        Member  48847.84
3  2024-02-01        Normal  45913.80
4  2024-03-01        Member  53345.30
5  2024-03-01        Normal  50898.04
6  2024-04-01        Member  73152.89
7  2024-04-01        Normal  58930.99
8  2024-05-01        Member  17193.01
9  2024-05-01        Normal  43762.77
10 2024-06-01        Member   8027.06
11 2024-06-01        Normal  20856.35
12 2024-07-01        Member   7089.63
13 2024-07-01        Normal  15078.40
14 2024-08-01        Member   6566.05
15 2024-08-01        Normal  12874.10
16 2024-09-01        Member  29073.61
17 2024-09-01        Normal  47816.46
18 2024-10-01        Member  32670.68
19 2024-10-01        Normal  39980.96
20 2024-11-01        Member  43596.27
21 2024-11-01        Normal  57821.36
22 2024-12-01        Member  61648.85
23 2024-12-01        Normal  56646.27

In [ ]:
# Revenue by gender monthly:
gender_month_revenue = (df.groupby(['Month', 'Gender'], as_index=False)['Revenue'].sum())
gender_month_revenue

        Month  Gender   Revenue
0  2024-01-01  Female  56322.84
1  2024-01-01    Male  54431.32
2  2024-02-01  Female  54560.23
3  2024-02-01    Male  40201.41
4  2024-03-01  Female  49912.75
5  2024-03-01    Male  54330.59
6  2024-04-01  Female  68074.77
7  2024-04-01    Male  64009.11
8  2024-05-01  Female  33034.22
9  2024-05-01    Male  27921.56
10 2024-06-01  Female  15450.62
11 2024-06-01    Male  13432.79
12 2024-07-01  Female  12012.68
13 2024-07-01    Male  10155.35
14 2024-08-01  Female  10419.94
15 2024-08-01    Male   9020.21
16 2024-09-01  Female  35304.27
17 2024-09-01    Male  41585.80
18 2024-10-01  Female  39050.11
19 2024-10-01    Male  33601.53
20 2024-11-01  Female  54842.51
21 2024-11-01    Male  46575.12
22 2024-12-01  Female  61184.78
23 2024-12-01    Male  57110.34

In [ ]:
# Prices product lines analysis:
# Food & Beverages
df_food = df[df['Product line'] == 'Food & Beverages']
df_food
daily_price_food = (df_food.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_food

          Date     Branch  Unit price
0   2024-01-01   Brooklyn      52.875
1   2024-01-02  Manhattan      41.660
2   2024-01-05   Brooklyn      71.200
3   2024-01-06  Manhattan      40.940
4   2024-01-06     Queens      89.480
..         ...        ...         ...
796 2024-12-30  Manhattan       2.330
797 2024-12-30     Queens       9.680
798 2024-12-31   Brooklyn       5.240
799 2024-12-31  Manhattan       7.675
800 2024-12-31     Queens       5.880

[801 rows x 3 columns]

In [ ]:
# Home & lifestyle
df_home = df[df['Product line'] == 'Home & Lifestyle']
df_home
daily_price_home = (df_home.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_home

          Date     Branch  Unit price
0   2024-01-01  Manhattan       47.59
1   2024-01-03   Brooklyn       63.15
2   2024-01-03  Manhattan       67.09
3   2024-01-04  Manhattan       35.54
4   2024-01-05   Brooklyn       35.38
..         ...        ...         ...
514 2024-12-30   Brooklyn       60.87
515 2024-12-30  Manhattan       66.44
516 2024-12-30     Queens       66.80
517 2024-12-31   Brooklyn       66.22
518 2024-12-31     Queens       59.64

[519 rows x 3 columns]

In [ ]:
# Health & Beauty
df_health = df[df['Product line'] == 'Health & Beauty']
df_health
daily_price_health = (df_health.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_health

          Date     Branch  Unit price
0   2024-01-01     Queens     62.8700
1   2024-01-02   Brooklyn     34.2100
2   2024-01-03   Brooklyn     62.0000
3   2024-01-03  Manhattan     46.5200
4   2024-01-03     Queens     48.5000
..         ...        ...         ...
619 2024-12-30   Brooklyn     46.7400
620 2024-12-30  Manhattan     39.1250
621 2024-12-30     Queens     41.9875
622 2024-12-31  Manhattan     25.3200
623 2024-12-31     Queens     49.7500

[624 rows x 3 columns]

In [ ]:
# Electronics
df_electronics = df[df['Product line'] == 'Electronics']
df_electronics
daily_price_electronix = (df_electronics.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_electronix

          Date     Branch  Unit price
0   2024-01-01   Brooklyn      74.710
1   2024-01-01  Manhattan      74.220
2   2024-01-01     Queens      63.220
3   2024-01-02   Brooklyn      22.010
4   2024-01-04   Brooklyn      72.170
..         ...        ...         ...
353 2024-12-29   Brooklyn      75.790
354 2024-12-30   Brooklyn      83.050
355 2024-12-30     Queens      85.800
356 2024-12-31  Manhattan      73.140
357 2024-12-31     Queens      82.885

[358 rows x 3 columns]

In [ ]:
# Sports & Travel
df_sport = df[df['Product line'] == 'Sports & Travel']
df_sport
daily_price_sport = (df_sport.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_sport

          Date     Branch  Unit price
0   2024-01-01  Manhattan      49.825
1   2024-01-01     Queens      33.100
2   2024-01-02   Brooklyn      44.630
3   2024-01-02  Manhattan      42.470
4   2024-01-02     Queens      31.670
..         ...        ...         ...
435 2024-12-30   Brooklyn      56.320
436 2024-12-30  Manhattan      68.385
437 2024-12-30     Queens      66.610
438 2024-12-31   Brooklyn      75.455
439 2024-12-31  Manhattan      65.630

[440 rows x 3 columns]

In [ ]:
# Fashion & Accs
df_fashion = df[df['Product line'] == 'Fashion & Accs']
df_fashion
daily_price_fashion = (df_fashion.groupby(['Date', 'Branch'], as_index=False)['Unit price'].mean())
daily_price_fashion

          Date     Branch  Unit price
0   2024-01-01  Manhattan       65.74
1   2024-01-02   Brooklyn       40.61
2   2024-01-02     Queens       99.82
3   2024-01-04   Brooklyn       68.71
4   2024-01-05   Brooklyn       73.96
..         ...        ...         ...
489 2024-12-29  Manhattan       14.81
490 2024-12-29     Queens        6.28
491 2024-12-30  Manhattan        4.41
492 2024-12-30     Queens       14.52
493 2024-12-31     Queens        3.01

[494 rows x 3 columns]

In [ ]:
# Analysis of quantity:
monthly_quantity = (df.groupby(['Month','Product line'], as_index=False)['Quantity'].mean())
monthly_quantity

        Month      Product line  Quantity
0  2024-01-01       Electronics  6.166667
1  2024-01-01    Fashion & Accs  5.250000
2  2024-01-01  Food & Beverages  5.803571
3  2024-01-01   Health & Beauty  5.183673
4  2024-01-01  Home & Lifestyle  5.796610
..        ...               ...       ...
67 2024-12-01    Fashion & Accs  5.414286
68 2024-12-01  Food & Beverages  5.752688
69 2024-12-01   Health & Beauty  5.738636
70 2024-12-01  Home & Lifestyle  6.015873
71 2024-12-01   Sports & Travel  5.431579

[72 rows x 3 columns]

In [ ]:
# Top product categories:
import plotly.express as px

fig = px.pie(
    df_top,
    names = 'Product line',
    values = 'Revenue',
    title = 'Top product categories',
    color_discrete_sequence=px.colors.qualitative.Pastel1
)
fig.show()

In [ ]:
# Time-based sales analysis: months
monthly_revenue['Month'] = monthly_revenue['Month'].astype(str)
fig = px.line(
    monthly_revenue,
    x = 'Month',
    y = 'Revenue',
    markers=True,
    color = 'Branch',
    title = 'Revenue analysis by month',

)
fig.update_traces(marker = dict(size = 15))
# fig.update_yaxes(type = 'log')

# fig.update_layout(width = 1100, height = 600, boxgap = 0.1, boxgroupgap = 0.1)
fig.show()

In [ ]:
# Unit price monthly analysis:
fig = px.line(
    monthly_price,
    x = 'Month',
    y = 'Unit price',
    markers=True,
    color = 'Branch',
    title = 'Prices analysis by month',

)
fig.update_traces(marker = dict(size = 15))

fig.show()

In [ ]:
# Types of payment:
fig = px.bar(
    cash_and_card,
    x = 'Payment',
    y = 'Revenue',
    color='Payment',
    title = 'Types of payment',
    text_auto=True,
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Revenue by branches:
fig = px.pie(
    branch_revenue,
    names = 'Branch',
    values='Revenue',
    title='Revenue by branches',
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Revenue during the weeks:
fig = px.bar(
    daily_revenue,
    x = 'Date',
    y = 'Revenue',
    color='Day_type',
    title = 'Revenue during the weeks',
    text_auto=True,
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Sales analysis by product line and branch:
fig = px.bar(
    analysis_prod_branch,
    x = 'Branch',
    y = 'Revenue',
    color = 'Product line',
    barmode='group',
    title='Sales analysis by product line and branch',
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Unit prices analysis by product lines:
fig = px.box(
    df,
    x = 'Product line',
    y = 'Unit price',
    color = "Product line",
    title='Unit prices analysis by product lines',
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Revenue by customer type monthly:
customer_month_revenue['Month'] = customer_month_revenue['Month'].astype(str)
fig = px.bar(
    customer_month_revenue,
    x = 'Month',
    y = 'Revenue',
    color = 'Customer type',
    title = 'Revenue by customer type monthly',
    color_discrete_sequence=px.colors.qualitative.Pastel1
)

fig.show()

In [ ]:
# Revenue by gender monthly:
gender_month_revenue['Month'] = gender_month_revenue['Month'].astype(str)
fig = px.bar(
    gender_month_revenue,
    x = 'Month',
    y = 'Revenue',
    color = 'Gender',
    title = 'Revenue by gender monthly',
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Food & Beverages
fig = px.bar(
    daily_price_food,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Food & Beverages average prices'
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Home & lifestyle
fig = px.bar(
    daily_price_home,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Home & lifestyle average prices'
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Health & Beauty
fig = px.bar(
    daily_price_health,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Health & Beauty average prices'
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Electronics
fig = px.bar(
    daily_price_electronix,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Electronics average prices'
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Sports & Travel
fig = px.bar(
    daily_price_sport,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Sports & Travel average prices'
)
fig.show()

In [ ]:
# Prices product lines analysis:
# Fashion & Accs
fig = px.bar(
    daily_price_fashion,
    x = 'Date',
    y = 'Unit price',
    color = 'Branch',
    title = 'Fashion & Accs average prices'
)
fig.show()

In [ ]:
# Rating analysis:
fig = px.histogram(
    df,
    x = 'Rating',
    barmode='overlay',
    title='Rating analysis'
)
fig.show()

In [ ]:
# Analysis of quantity:
fig = px.line(
    monthly_quantity,
    x = 'Month',
    y = 'Quantity',
    markers=True,
    color = 'Product line',
    title="Analysis of quantity"

)
fig.update_traces(marker = dict(size = 15))
fig.show()